version: '3.8'

services:
  web:
    build: .
    command: gunicorn datexns.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=datexns
      - POSTGRES_USER=datexns
      - POSTGRES_PASSWORD=Alles-01
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    env_file:
      - .env  # Воспользуйтесь файлом окружения для переменных среды

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: datexns
      POSTGRES_USER: datexns
      POSTGRES_PASSWORD: Alles-01
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"  # Открытие порта 5432 для подключения к базе данных

volumes:
  postgres_data:
